### ISSUE TITLE
How to use the default vega-lite Tooltip question

### ISSUE THREAD

**Issue by faramos** [redwerks/material-vega#27]
First of all, thank you for your contribution.
I tried MuiVegaLite successfully, with the exception of the tooltip. It is appearing in the wrong upper-left position, away from the cursor. I've already tried customizing the tooltip component with no success. If I use only the vega-lite component, the tooltip displays as expected.
Is there a way to use the native tooltip component?

Thanks in advance.

**Comment by dantman** [comment]
MuiVega sets the `tooltip` prop, so in theory something like `tooltip={undefined}` or maybe `null` should reset the behaviour to the Vega built-in.

**Comment by faramos** [comment]
tooltip={true} did the trick
